### ISSUE TITLE
way to disable, if mobileParser get it the detection wrong ? 

### ISSUE THREAD

**Issue by strimbob** [modosc/react-responsive-redux#7]
this this library  is great!

but i running into a problem, i get a double load on some assets, is there a way to only load it once and not check after bundle.js loads?

here is a screen shot to show what i mean
i am on a desktop with the width of the browser window small (>800px)

the server loads menuBarDtop.svg , then after the client loads it checks and then loads menuBarPhone.svg

is there a way to say go with what the sever has loaded?

![doubleload](https://user-images.githubusercontent.com/2370803/37588369-4e3c9fe0-2b62-11e8-9ed4-3abc62141805.jpg)
![screen shot 2018-03-19 at 10 33 19](https://user-images.githubusercontent.com/2370803/37588374-544f4a04-2b62-11e8-8bb7-751a36ecc9f8.png)

best
ben

**Comment by modosc** [comment]
the only way this would work currently is if you disable js on your browser - then you get the exact state the server returns.

otherwise it's (unfortunately) doing the right thing - there's no way to know the size of your browser window on the default request, hence grouping non-mobile/tablet browsers all as `desktop`.
